// Lives outside src/integrations/supabase/ on purpose: that folder is
// regenerated by the Lovable/Supabase codegen tooling and client.ts there is
// marked "automatically generated, do not edit directly" — anything added
// straight into client.ts can be silently wiped on the next regeneration.
//
// supabase-js's default auth lock coordinates getSession()/token-refresh across
// tabs via the browser's Web Locks API — but it has a well-documented deadlock
// class (see supabase/supabase-js #2013, #2111, #1517): an aborted/orphaned
// lock request (e.g. from React StrictMode double-invoking an effect) leaves
// every subsequent auth call queued behind a lock that's never released,
// hanging forever with no error. Reproduced directly in this app: a cold
// reload onto an authenticated /portal/* route rendered permanently blank
// because getSession() itself never resolved.
//
// This in-memory (same-tab-only) lock trades perfect cross-tab coordination
// for eliminating that deadlock class entirely — the right call for how this
// app is used. It's applied two ways so it survives client.ts regeneration:
// passed as the `lock` option at createClient() time in client.ts, AND
// re-asserted directly onto the auth client at app boot in main.tsx.
let authLockChain: Promise<void> = Promise.resolve();

export async function inMemoryAuthLock<R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> {
  const previous = authLockChain;
  let release: () => void = () => {};
  authLockChain = new Promise<void>(resolve => { release = resolve; });
  await previous.catch(() => {});
  try {
    return await fn();
  } finally {
    release();
  }
}
