import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { supabase } from "@/integrations/supabase/client";
import { inMemoryAuthLock } from "@/lib/supabaseAuthLock";

// Defensive re-assert: src/integrations/supabase/client.ts is regenerated by
// codegen tooling and could silently drop the custom `auth.lock` option that
// prevents a Supabase-js Web Locks deadlock (see supabaseAuthLock.ts). `lock`
// is a plain instance property read fresh on every auth call, so reassigning
// it here — outside the generated file — keeps the fix in effect even if
// client.ts reverts to its vanilla form.
(supabase.auth as unknown as { lock: typeof inMemoryAuthLock }).lock = inMemoryAuthLock;

createRoot(document.getElementById("root")!).render(<App />);
